<?xml version="1.0" encoding="utf-8"?><Database Name="salud" Class="ORMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JULIAN-PC\SQLEXPRESS;Initial Catalog=salud;Integrated Security=True" SettingsObjectName="Logica.Properties.Settings" SettingsPropertyName="saludConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.citas" Member="citas">
    <Type Name="citas">
      <Column Name="id_cita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_persona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_especialista" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hora_cita" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="especialista_citas" Member="especialista" ThisKey="id_especialista" OtherKey="id_especialista" Type="especialista" IsForeignKey="true" />
      <Association Name="persona_citas" Member="persona" ThisKey="id_persona" OtherKey="id_persona" Type="persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sintoma" Member="sintoma">
    <Type Name="sintoma">
      <Column Name="id_sintoma" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sintoma" Member="sintoma1" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="sintoma_enfermedad" Member="enfermedad" ThisKey="id_sintoma" OtherKey="id_sintoma" Type="enfermedad" />
    </Type>
  </Table>
  <Table Name="dbo.ciudad" Member="ciudad">
    <Type Name="ciudad">
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ciudad" Member="ciudad1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ciudad_ente_salud" Member="ente_salud" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ente_salud" />
      <Association Name="ciudad_especialista" Member="especialista" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="especialista" />
    </Type>
  </Table>
  <Table Name="dbo.enfermedad" Member="enfermedad">
    <Type Name="enfermedad">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="id_sintoma" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_recomendacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="sintoma_enfermedad" Member="sintoma" ThisKey="id_sintoma" OtherKey="id_sintoma" Type="sintoma" IsForeignKey="true" />
      <Association Name="recomendacion_enfermedad" Member="recomendacion" ThisKey="id_recomendacion" OtherKey="id_recomendacion" Type="recomendacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ente_salud" Member="ente_salud">
    <Type Name="ente_salud">
      <Column Name="id_ente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_persona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="razon_social" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="representante" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="sitio_web" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="capacidad_pacientes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ente_salud_especialista" Member="especialista" ThisKey="id_ente" OtherKey="id_ente_salud" Type="especialista" />
      <Association Name="ciudad_ente_salud" Member="ciudad" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudad" IsForeignKey="true" />
      <Association Name="persona_ente_salud" Member="persona" ThisKey="id_persona" OtherKey="id_persona" Type="persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.especialidades" Member="especialidades">
    <Type Name="especialidades">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_especialista" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="especialidad" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="especialista_especialidades" Member="especialista" ThisKey="id_especialista" OtherKey="id_especialista" Type="especialista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.especialista" Member="especialista">
    <Type Name="especialista">
      <Column Name="id_especialista" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_persona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ente_salud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="numero_de_licencia_de_salud" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fecha_de_expedicion_de_la_licencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="especialista_citas" Member="citas" ThisKey="id_especialista" OtherKey="id_especialista" Type="citas" />
      <Association Name="especialista_especialidades" Member="especialidades" ThisKey="id_especialista" OtherKey="id_especialista" Type="especialidades" />
      <Association Name="ciudad_especialista" Member="ciudad" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="ciudad" IsForeignKey="true" />
      <Association Name="ente_salud_especialista" Member="ente_salud" ThisKey="id_ente_salud" OtherKey="id_ente" Type="ente_salud" IsForeignKey="true" />
      <Association Name="persona_especialista" Member="persona" ThisKey="id_persona" OtherKey="id_persona" Type="persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.persona" Member="persona">
    <Type Name="persona">
      <Column Name="id_persona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cedula" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="persona_citas" Member="citas" ThisKey="id_persona" OtherKey="id_persona" Type="citas" />
      <Association Name="persona_ente_salud" Member="ente_salud" ThisKey="id_persona" OtherKey="id_persona" Type="ente_salud" />
      <Association Name="persona_especialista" Member="especialista" ThisKey="id_persona" OtherKey="id_persona" Type="especialista" />
      <Association Name="rol_persona" Member="rol" ThisKey="id_rol" OtherKey="id_rol" Type="rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.recomendacion" Member="recomendacion">
    <Type Name="recomendacion">
      <Column Name="id_recomendacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="recomendacion" Member="recomendacion1" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="recomendacion_enfermedad" Member="enfermedad" ThisKey="id_recomendacion" OtherKey="id_recomendacion" Type="enfermedad" />
    </Type>
  </Table>
  <Table Name="dbo.rol" Member="rol">
    <Type Name="rol">
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rol" Member="rol1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="rol_persona" Member="persona" ThisKey="id_rol" OtherKey="id_rol" Type="persona" />
    </Type>
  </Table>
</Database>